services:
  backend:
    image: 'gestion-matriculas-backend:latest'
    container_name: "gestion_matriculas_app"
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - CURSOS_PATH=${CURSOS_PATH}
      - ESTUDIANTES_PATH=${ESTUDIANTES_PATH}
      - REGISTROS_PATH=${REGISTROS_PATH}
    depends_on:
      - mongo_db

  mongo_db:
    image: 'mongo:latest'
    container_name: "mongodb"
    ports:
      - "27018:27018"
    volumes:
      - mongo-data:/data/db
    command: mongod --port 27018

volumes:
  mongo-data: